services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden

    restart: unless-stopped

    environment:
      - DOMAIN=https://vault.patelsahil.in
      - DATABASE_URL=postgresql://${VAULTWARDEN_DB_USER}:${VAULTWARDEN_DB_PASSWORD}@postgres:5432/${VAULTWARDEN_DB_NAME}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=true
      - INVITATIONS_ALLOWED=true
      - SHOW_PASSWORD_HINT=false
      - LOG_LEVEL=info

    volumes:
      - vaultwarden_data:/data

    networks:
      - proxy

    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`vault.patelsahil.in`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.middlewares=secure-headers@file,compress@file
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

    security_opt:
      - no-new-privileges:true

    env_file:
      - ../../.env

networks:
  proxy:
    external: true

volumes:
  vaultwarden_data:
