#!/bin/bash
set -e

# Create n8n Database and User
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $N8N_DB_USER WITH PASSWORD '$N8N_DB_PASSWORD';
	CREATE DATABASE $N8N_DB_NAME OWNER $N8N_DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE $N8N_DB_NAME TO $N8N_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$N8N_DB_NAME" <<-EOSQL
	GRANT ALL ON SCHEMA public TO $N8N_DB_USER;
EOSQL

# Create Nextcloud Database and User
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $NEXTCLOUD_DB_USER WITH PASSWORD '$NEXTCLOUD_DB_PASSWORD';
	CREATE DATABASE $NEXTCLOUD_DB_NAME OWNER $NEXTCLOUD_DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE $NEXTCLOUD_DB_NAME TO $NEXTCLOUD_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$NEXTCLOUD_DB_NAME" <<-EOSQL
	GRANT ALL ON SCHEMA public TO $NEXTCLOUD_DB_USER;
EOSQL

# Create Docmost Database and User
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $DOCMOST_DB_USER WITH PASSWORD '$DOCMOST_DB_PASSWORD';
	CREATE DATABASE $DOCMOST_DB_NAME OWNER $DOCMOST_DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE $DOCMOST_DB_NAME TO $DOCMOST_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DOCMOST_DB_NAME" <<-EOSQL
	GRANT ALL ON SCHEMA public TO $DOCMOST_DB_USER;
EOSQL

# Create Vaultwarden Database and User
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $VAULTWARDEN_DB_USER WITH PASSWORD '$VAULTWARDEN_DB_PASSWORD';
	CREATE DATABASE $VAULTWARDEN_DB_NAME OWNER $VAULTWARDEN_DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE $VAULTWARDEN_DB_NAME TO $VAULTWARDEN_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$VAULTWARDEN_DB_NAME" <<-EOSQL
	GRANT ALL ON SCHEMA public TO $VAULTWARDEN_DB_USER;
EOSQL
