title: HomeLab Dashboard
favicon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/favicon.ico

background: https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&w=1920&q=80

cardBlur: sm

theme: dark
color: zinc

headerStyle: boxed

layout:
  Administration & System:
    style: row
    columns: 3
  Dev & Automation:
    style: row
    columns: 3
  Monitoring & Telemetry:
    style: row
    columns: 3
  Personal Cloud & Media:
    style: row
    columns: 3
  AI Tools:
    style: row
    columns: 1

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  hideVisitURL: false

proxy:
  useCredentials: false

showStats: true
