services:

  traefik:

    image: traefik:v3.6.1

    container_name: traefik

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./certs:/etc/traefik/certs:ro
      - ./logs:/logs

    networks:
      - proxy

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.patelsahil.in`)
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.tls=true
      - traefik.http.routers.traefik-dashboard.service=api@internal

    security_opt:
      - no-new-privileges:true

  error-pages:
    image: tarampampam/error-pages:3.3.0
    container_name: error-pages
    restart: unless-stopped
    environment:
      TEMPLATE_NAME: ghost
      SHOW_DETAILS: "true"
    networks:
      - proxy

networks:
  proxy:
    external: true