services:

  cloudflared:

    image: cloudflare/cloudflared:2025.6.1

    container_name: cloudflared

    restart: unless-stopped

    command: tunnel --no-autoupdate run

    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=${TZ}

    dns:
      - 1.1.1.1
      - 8.8.8.8

    networks:
      - proxy

    security_opt:
      - no-new-privileges:true

networks:

  proxy:
    external: true